[project]
name = "pyspark-ml"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
dependencies = [
    "ipywidgets>=8.1.8",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.8",
    "pandas>=3.0.0",
    "plotly>=6.5.2",
    "pyspark>=4.1.1",
    "scikit-learn>=1.8.0",
    "tqdm>=4.67.3",
]
